#!/usr/bin/env bash

# ==========================================================
# Kali Zsh Config
# Main Installer
# ==========================================================

set -euo pipefail

# ----------------------------------------------------------
# Repository path
# ----------------------------------------------------------

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ----------------------------------------------------------
# Basic information
# ----------------------------------------------------------

echo
echo "=============================================="
echo "        Kali Zsh Config Installer"
echo "=============================================="
echo
echo "[+] Repository:"
echo "    $REPO_DIR"
echo

# ----------------------------------------------------------
# Required commands
# ----------------------------------------------------------

for cmd in bash zsh; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "[!] Required command not found: $cmd"
        exit 1
    fi
done

# ----------------------------------------------------------
# Required repository files
# ----------------------------------------------------------

REQUIRED_FILES=(
    "config/zshrc"
    "config/options.zsh"
    "config/aliases.zsh"
    "config/completion.zsh"
)

for file in "${REQUIRED_FILES[@]}"; do
    if [[ ! -f "$REPO_DIR/$file" ]]; then
        echo "[!] Missing required file:"
        echo "    $REPO_DIR/$file"
        exit 1
    fi
done

echo "[+] Required configuration files found."

# ----------------------------------------------------------
# Optional setup scripts
# ----------------------------------------------------------

if [[ -f "$REPO_DIR/setup/packages.sh" ]]; then
    echo
    echo "[+] Running package setup..."

    chmod +x "$REPO_DIR/setup/packages.sh"

    if "$REPO_DIR/setup/packages.sh"; then
        echo "[+] Package setup completed."
    else
        echo "[!] Package setup failed."
        exit 1
    fi
fi

if [[ -f "$REPO_DIR/setup/directories.sh" ]]; then
    echo
    echo "[+] Running directory setup..."

    chmod +x "$REPO_DIR/setup/directories.sh"

    if "$REPO_DIR/setup/directories.sh"; then
        echo "[+] Directory setup completed."
    else
        echo "[!] Directory setup failed."
        exit 1
    fi
fi

if [[ -f "$REPO_DIR/setup/plugins.sh" ]]; then
    echo
    echo "[+] Running plugin setup..."

    chmod +x "$REPO_DIR/setup/plugins.sh"

    if "$REPO_DIR/setup/plugins.sh"; then
        echo "[+] Plugin setup completed."
    else
        echo "[!] Plugin setup failed."
        exit 1
    fi
fi

# ----------------------------------------------------------
# Validate Zsh configuration BEFORE installation
# ----------------------------------------------------------

echo
echo "[+] Checking Zsh configuration..."

ZSH_FILES=(
    "config/zshrc"
    "config/options.zsh"
    "config/aliases.zsh"
    "config/completion.zsh"
)

for file in "${ZSH_FILES[@]}"; do
    if ! zsh -n "$REPO_DIR/$file"; then
        echo
        echo "[!] Syntax error in:"
        echo "    $REPO_DIR/$file"
        echo
        echo "[!] Installation stopped."
        exit 1
    fi
done

if [[ -f "$REPO_DIR/widgets/filesystem-preview.zsh" ]]; then
    if ! zsh -n "$REPO_DIR/widgets/filesystem-preview.zsh"; then
        echo
        echo "[!] Syntax error in:"
        echo "    widgets/filesystem-preview.zsh"
        exit 1
    fi
fi

if [[ -f "$REPO_DIR/widgets/tool-completion.zsh" ]]; then
    if ! zsh -n "$REPO_DIR/widgets/tool-completion.zsh"; then
        echo
        echo "[!] Syntax error in:"
        echo "    widgets/tool-completion.zsh"
        exit 1
    fi
fi

echo "[+] Zsh configuration syntax is valid."

# ----------------------------------------------------------
# Backup existing ~/.zshrc
# ----------------------------------------------------------

if [[ -f "$HOME/.zshrc" ]]; then

    echo
    echo "[+] Existing ~/.zshrc detected."

    BACKUP="$HOME/.zshrc.backup"

    if [[ -e "$BACKUP" ]]; then
        BACKUP="$HOME/.zshrc.backup.$(date +%Y%m%d-%H%M%S)"
    fi

    cp "$HOME/.zshrc" "$BACKUP"

    echo "[+] Backup created:"
    echo "    $BACKUP"

else
    echo
    echo "[+] No existing ~/.zshrc found."
fi

# ----------------------------------------------------------
# Create repository loader
# ----------------------------------------------------------

echo
echo "[+] Installing repository Zsh loader..."

TEMP_ZSHRC="$(mktemp)"

cat > "$TEMP_ZSHRC" <<EOF
# ==========================================================
# Kali Zsh Config
# Generated by install.sh
# ==========================================================

# Absolute path of the installed repository.
export KALI_ZSH_CONFIG_DIR="$REPO_DIR"

# Load the main repository configuration.
if [[ -f "\$KALI_ZSH_CONFIG_DIR/config/zshrc" ]]; then
    source "\$KALI_ZSH_CONFIG_DIR/config/zshrc"
else
    print -u2 "Kali Zsh Config: repository configuration not found:"
    print -u2 "  \$KALI_ZSH_CONFIG_DIR/config/zshrc"
fi
EOF

# ----------------------------------------------------------
# Validate generated ~/.zshrc BEFORE replacing it
# ----------------------------------------------------------

if ! zsh -n "$TEMP_ZSHRC"; then
    echo "[!] Generated ~/.zshrc failed syntax validation."
    rm -f "$TEMP_ZSHRC"
    exit 1
fi

# ----------------------------------------------------------
# Install generated ~/.zshrc
# ----------------------------------------------------------

mv "$TEMP_ZSHRC" "$HOME/.zshrc"

chmod 600 "$HOME/.zshrc"

echo "[+] ~/.zshrc installed successfully."

# ----------------------------------------------------------
# Verify repository path
# ----------------------------------------------------------

echo
echo "[+] Verifying repository path..."

if ! grep -Fq "export KALI_ZSH_CONFIG_DIR=\"$REPO_DIR\"" "$HOME/.zshrc"; then
    echo "[!] Repository path verification failed."
    exit 1
fi

if grep -Fq "/home/config/" "$HOME/.zshrc"; then
    echo "[!] Invalid /home/config/ path detected."
    exit 1
fi

echo "[+] Repository path verified."

# ----------------------------------------------------------
# Final configuration test
# ----------------------------------------------------------

echo
echo "[+] Final Zsh configuration test..."

TEST_OUTPUT="$(
    KALI_ZSH_CONFIG_DIR="$REPO_DIR" \
    zsh -ic 'print -r -- "$KALI_ZSH_CONFIG_DIR"' \
    2>&1
)" || {
    echo
    echo "[!] Zsh failed to load the configuration."
    echo
    echo "$TEST_OUTPUT"
    echo
    echo "[!] Your previous ~/.zshrc backup is still available."
    exit 1
}

if [[ "$TEST_OUTPUT" != "$REPO_DIR" ]]; then
    echo
    echo "[!] Repository path test failed."
    echo "Expected:"
    echo "    $REPO_DIR"
    echo "Got:"
    echo "    $TEST_OUTPUT"
    exit 1
fi

echo "[+] Zsh configuration loaded successfully."

# ----------------------------------------------------------
# Installation complete
# ----------------------------------------------------------

echo
echo "=============================================="
echo "     Installation completed successfully!"
echo "=============================================="
echo
echo "Repository:"
echo "    $REPO_DIR"
echo
echo "Zsh configuration:"
echo "    $HOME/.zshrc"
echo
echo "Existing configuration backup:"
echo "    $HOME/.zshrc.backup*"
echo
echo "IMPORTANT:"
echo "Start a fresh Zsh session with:"
echo
echo "    exec zsh"
echo
echo "The installer does NOT automatically execute"
echo "exec zsh, so your current shell is left untouched."
echo
