#!/usr/bin/env bash

set -euo pipefail

# ==========================================================
# Kali Zsh Config
# Main Installer
# ==========================================================

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$REPO_DIR/config/zshrc"
ZSHRC="$HOME/.zshrc"
BACKUP="$HOME/.zshrc.backup"

PLUGIN_DIR="$HOME/plugins"

# ----------------------------------------------------------
# Colors
# ----------------------------------------------------------

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
RESET='\033[0m'

info() {
    printf "${CYAN}[+]${RESET} %s\n" "$1"
}

success() {
    printf "${GREEN}[+]${RESET} %s\n" "$1"
}

warning() {
    printf "${YELLOW}[!]${RESET} %s\n" "$1"
}

error() {
    printf "${RED}[!]${RESET} %s\n" "$1" >&2
}

# ----------------------------------------------------------
# Basic checks
# ----------------------------------------------------------

if [[ "${EUID}" -eq 0 ]]; then
    error "Do not run this installer as root."
    error "Run it as your normal Kali user."
    exit 1
fi

if ! command -v zsh >/dev/null 2>&1; then
    error "Zsh is not installed."
    exit 1
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
    error "Configuration file not found:"
    error "$CONFIG_FILE"
    exit 1
fi

# ----------------------------------------------------------
# Repository information
# ----------------------------------------------------------

echo
info "Kali Zsh Config installer"
info "Repository:"
printf "    %s\n" "$REPO_DIR"
echo

# ----------------------------------------------------------
# Run setup modules
# ----------------------------------------------------------

if [[ -f "$REPO_DIR/setup/directories.sh" ]]; then
    info "Running directory setup..."
    source "$REPO_DIR/setup/directories.sh"
fi

if [[ -f "$REPO_DIR/setup/packages.sh" ]]; then
    info "Running package setup..."
    source "$REPO_DIR/setup/packages.sh"
fi

if [[ -f "$REPO_DIR/setup/plugins.sh" ]]; then
    info "Running plugin setup..."
    source "$REPO_DIR/setup/plugins.sh"
fi

# ----------------------------------------------------------
# Backup existing .zshrc
# ----------------------------------------------------------

if [[ -f "$ZSHRC" ]]; then

    if [[ ! -f "$BACKUP" ]]; then
        info "Backing up existing ~/.zshrc..."
        cp "$ZSHRC" "$BACKUP"
        success "Backup created:"
        printf "    %s\n" "$BACKUP"
    else
        warning "Backup already exists:"
        printf "    %s\n" "$BACKUP"
    fi

else
    info "No existing ~/.zshrc found."
fi

# ----------------------------------------------------------
# Validate repository configuration
# ----------------------------------------------------------

info "Checking Zsh configuration..."

if ! zsh -n "$CONFIG_FILE"; then
    error "Zsh configuration contains a syntax error."
    error "Installation stopped. Your existing ~/.zshrc was not replaced."
    exit 1
fi

success "Zsh configuration syntax is valid."

# ----------------------------------------------------------
# Create user .zshrc
# ----------------------------------------------------------

info "Installing repository Zsh configuration..."

cat > "$ZSHRC" <<EOF
# ==========================================================
# Kali Zsh Config
# Generated by install.sh
# ==========================================================

export KALI_ZSH_CONFIG_DIR="$REPO_DIR"

if [[ -f "\$KALI_ZSH_CONFIG_DIR/config/zshrc" ]]; then
    source "\$KALI_ZSH_CONFIG_DIR/config/zshrc"
fi
EOF

# ----------------------------------------------------------
# Final syntax check
# ----------------------------------------------------------

if ! zsh -n "$ZSHRC"; then
    error "Generated ~/.zshrc failed syntax validation."

    if [[ -f "$BACKUP" ]]; then
        warning "Restoring previous ~/.zshrc..."
        cp "$BACKUP" "$ZSHRC"
    fi

    exit 1
fi

# ----------------------------------------------------------
# Installation complete
# ----------------------------------------------------------

echo
success "Installation completed successfully!"
echo

printf "${CYAN}Repository:${RESET}\n"
printf "  %s\n\n" "$REPO_DIR"

printf "${CYAN}Configuration:${RESET}\n"
printf "  %s\n\n" "$ZSHRC"

if [[ -f "$BACKUP" ]]; then
    printf "${CYAN}Backup:${RESET}\n"
    printf "  %s\n\n" "$BACKUP"
fi

printf "${GREEN}Start a fresh Zsh session with:${RESET}\n"
printf "  exec zsh\n"
echo

printf "${YELLOW}Note:${RESET} The installer does not automatically restart your shell.\n"
echo
